export {
  SupportedLocales,
  DEFAULT_LOCALE,
  type SupportedLocale,
  LOCALE_METADATA,
  type LocaleMetadata,
  getLocaleMetadata,
} from '../domain/locales.js';
export {
  UserRole,
  type UserRoleType,
  ROLE_HIERARCHY,
  ResourceAction,
  type ResourceActionType,
  PermissionEffect,
  type PermissionEffectType,
  AuditStatus,
  type AuditStatusType,
  TenantStatus,
  type TenantStatusType,
  ResourceType,
  type ResourceTypeType,
  ApplicationContext,
  type ApplicationContextType,
  PermissionTargetType,
  type PermissionTargetTypeType,
  LoginIdentifierType,
  type LoginIdentifierTypeType,
} from '../domain/enums.js';
export type {
  IAMCapabilityDTO,
  ApplicationPermissionSyncItemDTO,
  ApplicationPermissionSyncDTO,
  NavigationMenuItemDTO,
  NavigationMenuGroupDTO,
} from '../domain/iam.dtos.js';
export type {
  PatientGender,
  PatientDTO,
  CreatePatientDTO,
  PractitionerType,
  PractitionerDTO,
  CreatePractitionerDTO,
  EncounterStatus,
  EncounterDTO,
  EncounterSummaryDTO,
  CreateEncounterDTO,
  HealthPlanDTO,
  ProcedureDTO,
} from '../domain/clinical.dtos.js';
export { ErrorCode, SuccessCode } from '../errors/index.js';
export type { ProblemDetail, ErrorCodeValue, SuccessCodeValue } from '../errors/index.js';
export type { BaseEntity, RepositoryInterface } from '../domain/entities.js';
export {
  ValueObject,
  Cpf,
  Cns,
  Cnpj,
  Cnes,
  Cep,
  Phone,
  Email,
  BirthDate,
  Uf,
  BRAZILIAN_UFS,
  BRAZILIAN_UF_NAMES,
  type BrazilianUfCode,
  type BrazilianRegion,
  Rg,
  Username,
  Name,
  PasswordPolicy,
  type PasswordValidationResult,
  Country,
  type CountryCode,
  STANDARD_COUNTRIES,
  type CountryOption,
} from '../domain/value-objects/index.js';
export {
  APP_RESOURCE_MANIFEST,
  type ResourceManifestItem,
  type AppResourceCode,
  type AppSectionCode,
} from '../domain/resources.manifest.js';
