import { ApplicationContext, ResourceType, UserRole } from './enums.js';

export interface ResourceManifestItem {
  readonly code: string;
  readonly section: 'attendance' | 'clinical' | 'financial' | 'registries' | 'management' | 'system' | 'platform' | 'account';
  readonly context: (typeof ApplicationContext)[keyof typeof ApplicationContext];
  readonly resourceType: (typeof ResourceType)[keyof typeof ResourceType];
  readonly labelKey: string;
  readonly icon: string;
  readonly route: string | null;
  readonly sortOrder: number;
  readonly minRole: (typeof UserRole)[keyof typeof UserRole];
  readonly description: string;
  readonly parentCode?: string | null;
}

/**
 * 🧱 Canonical Application Resources Manifest (SSOT)
 * Single Source of Truth for all Clinical, Financial, Operational, and Architecture resources.
 */
export const APP_RESOURCE_MANIFEST = [
  // ── 1. BUSINESS Context: Attendance ──
  {
    code: 'op_schedule',
    section: 'attendance',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_ATTENDANCE_SCHEDULE',
    icon: 'calendar',
    route: '/attendance/schedule',
    sortOrder: 10,
    minRole: UserRole.USER,
    description: 'Scheduling consultations, clinical calendar, and appointments',
  },
  {
    code: 'op_attendance',
    section: 'attendance',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_ATTENDANCE_QUEUE',
    icon: 'users',
    route: '/attendance/queue',
    sortOrder: 20,
    minRole: UserRole.USER,
    description: 'Reception, waiting queue, and patient triage',
  },

  // ── 2. BUSINESS Context: Clinical ──
  {
    code: 'op_patients',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_PATIENTS',
    icon: 'user-plus',
    route: '/clinical/patients',
    sortOrder: 30,
    minRole: UserRole.USER,
    description: 'General patient registry, medical history, and documents',
  },
  {
    code: 'op_consultations',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_CONSULTATIONS',
    icon: 'activity',
    route: '/clinical/consultations',
    sortOrder: 40,
    minRole: UserRole.USER,
    description: 'Outpatient medical consultations, prescriptions, and lab test requests',
  },
  {
    code: 'op_pep',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_PEP',
    icon: 'file-text',
    route: '/clinical/records',
    sortOrder: 50,
    minRole: UserRole.USER,
    description: 'Electronic Health Records (EHR), clinical timeline, and evolutions',
  },

  // ── 3. BUSINESS Context: Financial ──
  {
    code: 'op_billing',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_BILLING',
    icon: 'credit-card',
    route: '/financial/billing',
    sortOrder: 60,
    minRole: UserRole.USER,
    description: 'Invoice billing, TISS/TUSS claims, and medical fees',
  },
  {
    code: 'op_cashflow',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_CASHFLOW',
    icon: 'dollar-sign',
    route: '/financial/cash-flow',
    sortOrder: 70,
    minRole: UserRole.USER,
    description: 'Daily cash management, financial transactions, and cash flow',
  },
  {
    code: 'op_payables',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_PAYABLES',
    icon: 'credit-card',
    route: '/financial/payables',
    sortOrder: 80,
    minRole: UserRole.USER,
    description: 'Accounts payable, accounts receivable, and bank reconciliation',
  },

  // ── 4. BUSINESS Context: Registries ──
  {
    code: 'base_staff',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_STAFF',
    icon: 'user-check',
    route: '/registries/staff',
    sortOrder: 90,
    minRole: UserRole.USER,
    description: 'Staff directory, clinical team, and administrative employees',
  },
  {
    code: 'base_health_plans',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_HEALTH_PLANS',
    icon: 'building',
    route: '/registries/health-plans',
    sortOrder: 100,
    minRole: UserRole.USER,
    description: 'Health insurance operators, accredited plans, and coverage rules',
  },
  {
    code: 'base_procedures',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_PROCEDURES',
    icon: 'syringe',
    route: '/registries/procedures',
    sortOrder: 110,
    minRole: UserRole.USER,
    description: 'Procedures catalog, TUSS table, and medical pricing',
  },
  {
    code: 'base_shifts',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_SHIFTS',
    icon: 'clock',
    route: '/registries/shifts',
    sortOrder: 115,
    minRole: UserRole.USER,
    description: 'Work shifts, duty rosters, and care schedules',
  },

  // ── 5. BUSINESS Context: Management ──
  {
    code: 'menu_mgmt_indicators',
    section: 'management',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_MGMT_INDICATORS',
    icon: 'trending-up',
    route: '/management/metrics',
    sortOrder: 120,
    minRole: UserRole.USER,
    description: 'Executive dashboard, clinic occupancy rate, and clinical metrics',
  },
  {
    code: 'menu_mgmt_reports',
    section: 'management',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_MGMT_REPORTS',
    icon: 'bar-chart-2',
    route: '/management/reports',
    sortOrder: 130,
    minRole: UserRole.USER,
    description: 'Analytical management reports, revenue, and clinical productivity',
  },

  // ── 6. ARCH Context: System ──
  {
    code: 'menu_sys_settings',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_SETTINGS',
    icon: 'sliders',
    route: '/system/settings',
    sortOrder: 200,
    minRole: UserRole.ADMIN,
    description: 'System preferences, scheduling rules, operating hours, and operational policies',
  },
  {
    code: 'menu_sys_users',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_USERS',
    icon: 'users',
    route: '/system/users',
    sortOrder: 210,
    minRole: UserRole.ADMIN,
    description: 'User accounts management, access profiles, and RBAC matrix',
  },
  {
    code: 'menu_sys_institution',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_INSTITUTION',
    icon: 'building',
    route: '/system/organizations',
    sortOrder: 220,
    minRole: UserRole.ADMIN,
    description: 'Clinic organizational details, fiscal registration, logo, and technical leads',
  },
  {
    code: 'menu_sys_audit',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_AUDIT',
    icon: 'shield',
    route: '/system/audit-logs',
    sortOrder: 230,
    minRole: UserRole.ADMIN,
    description: 'Immutable audit trail, EHR access logs, and compliance records',
  },

  // ── 7. ARCH Context: Platform (Exclusive to OWNER) ──
  {
    code: 'menu_platform_settings',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_SETTINGS',
    icon: 'sliders',
    route: '/platform/settings',
    sortOrder: 300,
    minRole: UserRole.OWNER,
    description: 'Global infrastructure parameters, authentication, and security governance',
  },
  {
    code: 'menu_platform_tenants',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_TENANTS',
    icon: 'grid',
    route: '/platform/tenants',
    sortOrder: 310,
    minRole: UserRole.OWNER,
    description: 'Multi-tenant organization management, instance isolation, and provisioning',
  },
  {
    code: 'menu_platform_api_keys',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_API_KEYS',
    icon: 'key',
    route: '/platform/api-keys',
    sortOrder: 320,
    minRole: UserRole.OWNER,
    description: 'API keys management for integrations and M2M credentials',
  },
  {
    code: 'menu_platform_webhooks',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_WEBHOOKS',
    icon: 'share-2',
    route: '/platform/integrations',
    sortOrder: 330,
    minRole: UserRole.OWNER,
    description: 'External connectors, event queues, orchestration, and webhooks',
  },
  {
    code: 'menu_platform_policies',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_POLICIES',
    icon: 'file-text',
    route: '/platform/policies',
    sortOrder: 340,
    minRole: UserRole.OWNER,
    description: 'Terms of service, privacy policies, and compliance agreements',
  },

  // ── 8. ARCH Context: User Account ──
  {
    code: 'menu_profile',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_PROFILE',
    icon: 'user',
    route: '/account/profile',
    sortOrder: 400,
    minRole: UserRole.USER,
    description: 'Viewing and editing user account profile details',
  },
  {
    code: 'menu_password',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_SECURITY',
    icon: 'key',
    route: '/account/security',
    sortOrder: 410,
    minRole: UserRole.USER,
    description: 'Credential management and password reset',
  },
  {
    code: 'menu_help',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_HELP',
    icon: 'help-circle',
    route: '/help',
    sortOrder: 420,
    minRole: UserRole.USER,
    description: 'Help center, technical documentation, and support tickets',
  },
] as const satisfies readonly ResourceManifestItem[];

export type AppResourceCode = (typeof APP_RESOURCE_MANIFEST)[number]['code'];
export type AppSectionCode = (typeof APP_RESOURCE_MANIFEST)[number]['section'];
