import { ApplicationContext, ResourceType, UserRole } from './enums.js';

export interface ResourceManifestItem {
  readonly code: string;
  readonly section: 'attendance' | 'clinical' | 'financial' | 'registries' | 'management' | 'system' | 'platform' | 'account';
  readonly context: (typeof ApplicationContext)[keyof typeof ApplicationContext];
  readonly resourceType: (typeof ResourceType)[keyof typeof ResourceType];
  readonly labelKey: string;
  readonly icon: string;
  readonly route: string | null;
  readonly sortOrder: number;
  readonly minRole: (typeof UserRole)[keyof typeof UserRole];
  readonly description: string;
  readonly parentCode?: string | null;
}

/**
 * 🧱 Canonical Application Resources Manifest (SSOT)
 * Single Source of Truth for all Clinical, Financial, Operational, and Architecture resources.
 */
export const APP_RESOURCE_MANIFEST = [
  // ── 1. Contexto BUSINESS: ATENDIMENTO ──
  {
    code: 'op_schedule',
    section: 'attendance',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_ATTENDANCE_SCHEDULE',
    icon: 'calendar',
    route: '/attendance/schedule',
    sortOrder: 10,
    minRole: UserRole.USER,
    description: 'Agendamento de consultas, calendário clínico e marcações',
  },
  {
    code: 'op_attendance',
    section: 'attendance',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_ATTENDANCE_QUEUE',
    icon: 'users',
    route: '/attendance/queue',
    sortOrder: 20,
    minRole: UserRole.USER,
    description: 'Recepção, fila de espera e triagem de pacientes',
  },

  // ── 2. Contexto BUSINESS: CLÍNICO ──
  {
    code: 'op_patients',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_PATIENTS',
    icon: 'user-plus',
    route: '/clinical/patients',
    sortOrder: 30,
    minRole: UserRole.USER,
    description: 'Cadastro geral de pacientes, histórico e documentos',
  },
  {
    code: 'op_consultations',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_CONSULTATIONS',
    icon: 'activity',
    route: '/clinical/consultations',
    sortOrder: 40,
    minRole: UserRole.USER,
    description: 'Atendimento médico ambulatorial, receitas e solicitações de exames',
  },
  {
    code: 'op_pep',
    section: 'clinical',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_CLINICAL_PEP',
    icon: 'file-text',
    route: '/clinical/records',
    sortOrder: 50,
    minRole: UserRole.USER,
    description: 'Prontuário Eletrônico do Paciente, histórico clínico e evoluções',
  },

  // ── 3. Contexto BUSINESS: FINANCEIRO ──
  {
    code: 'op_billing',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_BILLING',
    icon: 'credit-card',
    route: '/financial/billing',
    sortOrder: 60,
    minRole: UserRole.USER,
    description: 'Fechamento de faturas, guias TISS/TUSS e repasses médicos',
  },
  {
    code: 'op_cashflow',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_CASHFLOW',
    icon: 'dollar-sign',
    route: '/financial/cash-flow',
    sortOrder: 70,
    minRole: UserRole.USER,
    description: 'Caixa diário, movimentações financeiras e fluxo de caixa',
  },
  {
    code: 'op_payables',
    section: 'financial',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_FINANCIAL_PAYABLES',
    icon: 'credit-card',
    route: '/financial/payables',
    sortOrder: 80,
    minRole: UserRole.USER,
    description: 'Gestão de contas a pagar, títulos a receber e conciliação',
  },

  // ── 4. Contexto BUSINESS: CADASTROS ──
  {
    code: 'base_staff',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_STAFF',
    icon: 'user-check',
    route: '/registries/staff',
    sortOrder: 90,
    minRole: UserRole.USER,
    description: 'Cadastro de colaboradores, equipe assistencial e administrativa',
  },
  {
    code: 'base_health_plans',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_HEALTH_PLANS',
    icon: 'building',
    route: '/registries/health-plans',
    sortOrder: 100,
    minRole: UserRole.USER,
    description: 'Operadoras de saúde, planos credenciados e regras de autorização',
  },
  {
    code: 'base_procedures',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_PROCEDURES',
    icon: 'syringe',
    route: '/registries/procedures',
    sortOrder: 110,
    minRole: UserRole.USER,
    description: 'Catálogo de procedimentos, tabela TUSS e valores',
  },
  {
    code: 'base_shifts',
    section: 'registries',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_BASE_SHIFTS',
    icon: 'clock',
    route: '/registries/shifts',
    sortOrder: 115,
    minRole: UserRole.USER,
    description: 'Escalas de trabalho, plantões assistenciais e turnos de atendimento',
  },

  // ── 5. Contexto BUSINESS: GESTÃO ──
  {
    code: 'menu_mgmt_indicators',
    section: 'management',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_MGMT_INDICATORS',
    icon: 'trending-up',
    route: '/management/metrics',
    sortOrder: 120,
    minRole: UserRole.USER,
    description: 'Painel executivo de indicadores, taxa de ocupação e métricas clínicas',
  },
  {
    code: 'menu_mgmt_reports',
    section: 'management',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.BUSINESS,
    labelKey: 'NAV_MGMT_REPORTS',
    icon: 'bar-chart-2',
    route: '/management/reports',
    sortOrder: 130,
    minRole: UserRole.USER,
    description: 'Relatórios gerenciais analíticos, faturamento e produtividade',
  },

  // ── 6. Contexto ARCH: SISTEMA ──
  {
    code: 'menu_sys_settings',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_SETTINGS',
    icon: 'sliders',
    route: '/system/settings',
    sortOrder: 200,
    minRole: UserRole.ADMIN,
    description: 'Regras de funcionamento, agendamentos, horários operacionais e preferências',
  },
  {
    code: 'menu_sys_users',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_USERS',
    icon: 'users',
    route: '/system/users',
    sortOrder: 210,
    minRole: UserRole.ADMIN,
    description: 'Gestão de contas, colaboradores, perfis de acesso e matriz RBAC',
  },
  {
    code: 'menu_sys_institution',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_INSTITUTION',
    icon: 'building',
    route: '/system/organizations',
    sortOrder: 220,
    minRole: UserRole.ADMIN,
    description: 'Dados cadastrais da clínica, CNPJ, CNES, logotipo e responsáveis técnicos',
  },
  {
    code: 'menu_sys_audit',
    section: 'system',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_SYS_AUDIT',
    icon: 'shield',
    route: '/system/audit-logs',
    sortOrder: 230,
    minRole: UserRole.ADMIN,
    description: 'Trilha de auditoria imutável, logs de acesso aos prontuários e LGPD',
  },

  // ── 7. Contexto ARCH: PLATAFORMA (Exclusivo OWNER) ──
  {
    code: 'menu_platform_settings',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_SETTINGS',
    icon: 'sliders',
    route: '/platform/settings',
    sortOrder: 300,
    minRole: UserRole.OWNER,
    description: 'Parâmetros globais de infraestrutura, autenticação e segurança',
  },
  {
    code: 'menu_platform_tenants',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_TENANTS',
    icon: 'grid',
    route: '/platform/tenants',
    sortOrder: 310,
    minRole: UserRole.OWNER,
    description: 'Gestão multi-tenant de contratantes, instâncias e isolamento',
  },
  {
    code: 'menu_platform_api_keys',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_API_KEYS',
    icon: 'key',
    route: '/platform/api-keys',
    sortOrder: 320,
    minRole: UserRole.OWNER,
    description: 'Gestão de chaves de API para integrações e credenciais M2M',
  },
  {
    code: 'menu_platform_webhooks',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_WEBHOOKS',
    icon: 'share-2',
    route: '/platform/integrations',
    sortOrder: 330,
    minRole: UserRole.OWNER,
    description: 'Conectores externos, filas de eventos, orquestração e webhooks',
  },
  {
    code: 'menu_platform_policies',
    section: 'platform',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'NAV_PLATFORM_POLICIES',
    icon: 'file-text',
    route: '/platform/policies',
    sortOrder: 340,
    minRole: UserRole.OWNER,
    description: 'Termos de uso, políticas de privacidade e acordos DPA/LGPD',
  },

  // ── 8. Contexto ARCH: CONTA DO USUÁRIO ──
  {
    code: 'menu_profile',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_PROFILE',
    icon: 'user',
    route: '/account/profile',
    sortOrder: 400,
    minRole: UserRole.USER,
    description: 'Visualização e edição dos dados cadastrais do perfil do usuário',
  },
  {
    code: 'menu_password',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_SECURITY',
    icon: 'key',
    route: '/account/security',
    sortOrder: 410,
    minRole: UserRole.USER,
    description: 'Alteração de credenciais e senha de acesso',
  },
  {
    code: 'menu_help',
    section: 'account',
    parentCode: null,
    resourceType: ResourceType.MENU,
    context: ApplicationContext.ARCH,
    labelKey: 'USER_MENU_HELP',
    icon: 'help-circle',
    route: '/help',
    sortOrder: 420,
    minRole: UserRole.USER,
    description: 'Central de ajuda, documentação e abertura de chamados',
  },
] as const satisfies readonly ResourceManifestItem[];

export type AppResourceCode = (typeof APP_RESOURCE_MANIFEST)[number]['code'];
export type AppSectionCode = (typeof APP_RESOURCE_MANIFEST)[number]['section'];
